site_name: Ryan's Docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg